#pragma once

#ifndef TEXTURES_
#define TEXTURES_
enum Textures {
  BRICK_WALL,
  FINE_STONE_WALL,
  DIRT_WALL,
  STONE_WALL,
  STONE_WALL_WITH_BLOOD,
  AMMOPACK,
  MEDPACK,
  SHOTGUN,
  SHELLPACK,
};
#endif

#define DEFAULT_PLAYER_MOVE_SPEED 5.0f

#define WINDOW_WIDTH 1250
#define WINDOW_HEIGHT 900
#define WINDOW_HALF_WIDTH WINDOW_WIDTH / 2
#define WINDOWN_HALF_HEIGHT WINDOW_HEIGHT / 2

#define NUM_RAYS 200

#define DEFAULT_FOV PI / 3
#define DEFAULT_HALF_FOV DEFAULT_FOV / 2
#define DELTA_ANGLE DEFAULT_FOV / NUM_RAYS

#define HORIZONTAL_RESOLUTION WINDOW_WIDTH / NUM_RAYS
#define EPS 1
#define RAYCAST_MAX_RANGE 30

#define WALL_HEIGHT 125
#define WALL_HALF_HEIGHT 63
#define WALL_SIZE 125
#define SCREEN_DIST WINDOW_HALF_WIDTH / (tan(DEFAULT_HALF_FOV))
